# java_webdev

###
# @name create project
POST localhost:8080/projects
Content-Type: application/json

{
    "name": "Без имени",
    "description": "",
    "begin": "2024-02-22",
    "end": "2024-02-29"
}

###
# @name mod project
PUT localhost:8080/projects/1
Content-Type: application/json

{
    "name": "Проект 1",
    "description": "Тестовый проект котрый не имеет какого либо смысла",
    "begin": "2024-02-22",
    "end": "2024-02-23"
}

###
# @name get project by id
GET localhost:8080/projects/1

###
# @name get project by range
GET localhost:8080/projects?
    start_date=2024-02-22&
    end_date=2024-02-29

###
# @name delete project
DELETE localhost:8080/projects/4